var firstName = 'Michal';
var lastName = 'Zelewski'; 
var age = 29; 
var dateOfBirth = '04/20/1988'; 
var address = '2510 Portage Ave';
console.log('first name:', firstName);
console.log('last name:', lastName);
console.log('age:', age);
console.log('date of birth:', dateOfBirth);
console.log('address:', address);