let firstName = 'Michal';
let lastName = 'Zelewski'; 
let age = 29;
let dateOfBirth = '04/20/1988'; 
let address = '2510 Portage Ave';
console.log('first name:', firstName);
console.log('last name:', lastName);
console.log('age:', age);
console.log('date of birth:', dateOfBirth);
console.log('address:', address);