var firstName = 'Michal';
var lastName = 'Zelewski'; 
var age = 29; 
var dateOfBirth = '04/20/1988'; 
var address = '2510 Portage Ave';
//console.log(firstName);
//console.log(lastName);
//console.log(age);
//console.log(dateOfBirth);
//console.log(address);
console.log(firstName, lastName, age, dateOfBirth, address);